### ISSUE TITLE
Modify Docker Conatainer Start Commands with detached "-it" & reverse start order

### ISSUE THREAD

**Issue by arosenmund** [Oofles/network-threat-hunting-workshop#1]
sudo docker run -it --name th-elasticsearch --net th-elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" oofles/th-elasticsearch
sudo docker run -it --name th-kibana --net th-elastic -p 5601:5601 -e "ELASTICSEARCH_HOSTS=http://th-elasticsearch:9200" oofles/th-kibana

**Comment by arosenmund** [comment]
No this one!

sudo docker run -d --name th-elasticsearch --net th-elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" oofles/th-elasticsearch
sudo docker run -d --name th-kibana --net th-elastic -p 5601:5601 -e "ELASTICSEARCH_HOSTS=http://th-elasticsearch:9200/" oofles/th-kibana

**Comment by Oofles** [comment]
Resolved!
